name: SilentSMS
options:
  xcodeVersion: "15.0" # Projeyi Xcode 15 formatında oluştur
  bundleIdPrefix: com.mustafa
targets:
  SilentSMS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [SilentSMSApp.swift, ContentView.swift, SharedLogic.swift]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mustafa.SilentSMS
  SilentSMSExtension:
    type: app-extension
    platform: iOS
    sources: [MessageFilterExtension.swift, SharedLogic.swift]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mustafa.SilentSMS.Extension
